# Generated by Django 5.2.6 on 2025-09-23 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieTitle', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Musical', 'Musical'), ('War', 'War'), ('Western', 'Western')], default='Action', max_length=100)),
                ('duration', models.TimeField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TheaterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheaterName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('Rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_start', models.CharField(blank=True, choices=[('10:00 AM', '10:00 AM'), ('1:00 PM', '1:00 PM'), ('4:00 PM', '4:00 PM'), ('7:00 PM', '7:00 PM'), ('10:00 PM', '10:00 PM')], max_length=8, null=True)),
                ('show_end', models.CharField(blank=True, choices=[('12:30 PM', '12:30 PM'), ('3:30 PM', '3:30 PM'), ('6:30 PM', '6:30 PM'), ('9:30 PM', '9:30 PM'), ('12:30 AM', '12:30 AM')], max_length=8, null=True)),
                ('available_seats', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.moviename')),
                ('TheaterNameshow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.theatername')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('column', models.IntegerField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='CustomerApp.theatername')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('booked', models.BooleanField(default=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('MovieNamed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.moviename')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seats', models.ManyToManyField(to='CustomerApp.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.showtime')),
                ('TheaterNameBooked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.theatername')),
            ],
        ),
    ]
