# Generated by Django 5.2.6 on 2025-09-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieticketbooking',
            name='MovieNamed',
        ),
    ]
