# Generated by Django 5.2.6 on 2025-09-23 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieTitle', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Musical', 'Musical'), ('War', 'War'), ('Western', 'Western')], default='Action', max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieTicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('available_seats', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheaterName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('Rows', models.IntegerField()),
                ('SeatsPerRow', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('booked', models.BooleanField(default=False)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.showtime')),
            ],
        ),
        migrations.DeleteModel(
            name='otpModel',
        ),
        migrations.AddField(
            model_name='movieticketbooking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.showtime'),
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.theatername'),
        ),
        migrations.AddField(
            model_name='movieticketbooking',
            name='seats',
            field=models.ManyToManyField(to='CustomerApp.tickets'),
        ),
    ]
